### ISSUE TITLE
[1.0] 404 is bugged because of the catch all route (Bad bad Johnny)

### ISSUE THREAD

**Issue by johnnymast** [johnnymast/myio#18]
This is whats causing this issue:

https://github.com/johnnymast/myio/blob/master/routes/web.php#L55

Example error:
(URL: http://myio.nl2nd.com/register.html)
UnexpectedValueException in Response.php line 444:
The Response content must be a string or object implementing __toString(), "object" given.

**Comment by johnnymast** [comment]
The binding is located here https://github.com/johnnymast/myio/blob/master/app/Providers/AppServiceProvider.php#L20

**Comment by stevepop** [comment]
Issue resolved.
