### ISSUE TITLE
[1.0] Data too long for column 'url' at row 1

### ISSUE THREAD

**Issue by johnnymast** [johnnymast/myio#28]
ricardo [9:06 PM] 
found another bug. what me to say here or open a bug on github? 
ok. the create input field doesn't limit the text. I've pasted 60 paragraphs from lipsum.com and blew up

[9:10]  
Illuminate \ Database \ QueryException (22001)
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url' at row 1 (SQL: insert into `links` (`url`, `hash`, `updated_at`, `created_at`) values

[9:10]  
needs to be sanitized first

**Comment by stevepop** [comment]
This issue is now fixed in PR https://github.com/johnnymast/myio/pull/57

**Comment by stevepop** [comment]
Closing this issue now. Resolved.
